ALTER TABLE "PlatformExpense"
ADD COLUMN "recurrence" TEXT NOT NULL DEFAULT 'ONE_TIME',
ADD COLUMN "dueDay" INTEGER,
ADD COLUMN "nextDueDate" TIMESTAMP(3),
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
