export type PhoneCountryOption = {
  iso: string;
  code: string;
  flag: string;
  label: string;
};

export const PHONE_COUNTRIES: PhoneCountryOption[] = [
  { iso: "TR", code: "90", flag: "🇹🇷", label: "تركيا" },
  { iso: "SA", code: "966", flag: "🇸🇦", label: "السعودية" },
  { iso: "YE", code: "967", flag: "🇾🇪", label: "اليمن" },
  { iso: "EG", code: "20", flag: "🇪🇬", label: "مصر" },
  { iso: "JO", code: "962", flag: "🇯🇴", label: "الأردن" },
  { iso: "SY", code: "963", flag: "🇸🇾", label: "سوريا" },
  { iso: "PS", code: "970", flag: "🇵🇸", label: "فلسطين" },
  { iso: "AE", code: "971", flag: "🇦🇪", label: "الإمارات" },
  { iso: "QA", code: "974", flag: "🇶🇦", label: "قطر" },
  { iso: "KW", code: "965", flag: "🇰🇼", label: "الكويت" },
  { iso: "BH", code: "973", flag: "🇧🇭", label: "البحرين" },
  { iso: "OM", code: "968", flag: "🇴🇲", label: "عمان" },
  { iso: "IQ", code: "964", flag: "🇮🇶", label: "العراق" },
  { iso: "LB", code: "961", flag: "🇱🇧", label: "لبنان" },
  { iso: "MA", code: "212", flag: "🇲🇦", label: "المغرب" },
  { iso: "DZ", code: "213", flag: "🇩🇿", label: "الجزائر" },
  { iso: "TN", code: "216", flag: "🇹🇳", label: "تونس" },
  { iso: "LY", code: "218", flag: "🇱🇾", label: "ليبيا" },
  { iso: "SD", code: "249", flag: "🇸🇩", label: "السودان" },
  { iso: "SO", code: "252", flag: "🇸🇴", label: "الصومال" },
  { iso: "DJ", code: "253", flag: "🇩🇯", label: "جيبوتي" },
  { iso: "MR", code: "222", flag: "🇲🇷", label: "موريتانيا" },
  { iso: "KM", code: "269", flag: "🇰🇲", label: "جزر القمر" },
  { iso: "US", code: "1", flag: "🇺🇸", label: "الولايات المتحدة" },
  { iso: "CA", code: "1", flag: "🇨🇦", label: "كندا" },
  { iso: "GB", code: "44", flag: "🇬🇧", label: "المملكة المتحدة" },
  { iso: "AF", code: "93", flag: "🇦🇫", label: "أفغانستان" },
  { iso: "AL", code: "355", flag: "🇦🇱", label: "ألبانيا" },
  { iso: "AD", code: "376", flag: "🇦🇩", label: "أندورا" },
  { iso: "AO", code: "244", flag: "🇦🇴", label: "أنغولا" },
  { iso: "AI", code: "1", flag: "🇦🇮", label: "أنغويلا" },
  { iso: "AG", code: "1", flag: "🇦🇬", label: "أنتيغوا وباربودا" },
  { iso: "AR", code: "54", flag: "🇦🇷", label: "الأرجنتين" },
  { iso: "AM", code: "374", flag: "🇦🇲", label: "أرمينيا" },
  { iso: "AW", code: "297", flag: "🇦🇼", label: "أروبا" },
  { iso: "AU", code: "61", flag: "🇦🇺", label: "أستراليا" },
  { iso: "AT", code: "43", flag: "🇦🇹", label: "النمسا" },
  { iso: "AZ", code: "994", flag: "🇦🇿", label: "أذربيجان" },
  { iso: "BS", code: "1", flag: "🇧🇸", label: "الباهاما" },
  { iso: "BD", code: "880", flag: "🇧🇩", label: "بنغلاديش" },
  { iso: "BB", code: "1", flag: "🇧🇧", label: "بربادوس" },
  { iso: "BY", code: "375", flag: "🇧🇾", label: "بيلاروسيا" },
  { iso: "BE", code: "32", flag: "🇧🇪", label: "بلجيكا" },
  { iso: "BZ", code: "501", flag: "🇧🇿", label: "بليز" },
  { iso: "BJ", code: "229", flag: "🇧🇯", label: "بنين" },
  { iso: "BM", code: "1", flag: "🇧🇲", label: "برمودا" },
  { iso: "BT", code: "975", flag: "🇧🇹", label: "بوتان" },
  { iso: "BO", code: "591", flag: "🇧🇴", label: "بوليفيا" },
  { iso: "BA", code: "387", flag: "🇧🇦", label: "البوسنة والهرسك" },
  { iso: "BW", code: "267", flag: "🇧🇼", label: "بوتسوانا" },
  { iso: "BR", code: "55", flag: "🇧🇷", label: "البرازيل" },
  { iso: "BN", code: "673", flag: "🇧🇳", label: "بروناي" },
  { iso: "BG", code: "359", flag: "🇧🇬", label: "بلغاريا" },
  { iso: "BF", code: "226", flag: "🇧🇫", label: "بوركينا فاسو" },
  { iso: "BI", code: "257", flag: "🇧🇮", label: "بوروندي" },
  { iso: "KH", code: "855", flag: "🇰🇭", label: "كمبوديا" },
  { iso: "CM", code: "237", flag: "🇨🇲", label: "الكاميرون" },
  { iso: "CV", code: "238", flag: "🇨🇻", label: "الرأس الأخضر" },
  { iso: "KY", code: "1", flag: "🇰🇾", label: "جزر كايمان" },
  { iso: "CF", code: "236", flag: "🇨🇫", label: "أفريقيا الوسطى" },
  { iso: "TD", code: "235", flag: "🇹🇩", label: "تشاد" },
  { iso: "CL", code: "56", flag: "🇨🇱", label: "تشيلي" },
  { iso: "CN", code: "86", flag: "🇨🇳", label: "الصين" },
  { iso: "CO", code: "57", flag: "🇨🇴", label: "كولومبيا" },
  { iso: "CG", code: "242", flag: "🇨🇬", label: "الكونغو" },
  { iso: "CD", code: "243", flag: "🇨🇩", label: "الكونغو الديمقراطية" },
  { iso: "CR", code: "506", flag: "🇨🇷", label: "كوستاريكا" },
  { iso: "CI", code: "225", flag: "🇨🇮", label: "ساحل العاج" },
  { iso: "HR", code: "385", flag: "🇭🇷", label: "كرواتيا" },
  { iso: "CU", code: "53", flag: "🇨🇺", label: "كوبا" },
  { iso: "CY", code: "357", flag: "🇨🇾", label: "قبرص" },
  { iso: "CZ", code: "420", flag: "🇨🇿", label: "التشيك" },
  { iso: "DK", code: "45", flag: "🇩🇰", label: "الدنمارك" },
  { iso: "DM", code: "1", flag: "🇩🇲", label: "دومينيكا" },
  { iso: "DO", code: "1", flag: "🇩🇴", label: "الدومينيكان" },
  { iso: "EC", code: "593", flag: "🇪🇨", label: "الإكوادور" },
  { iso: "SV", code: "503", flag: "🇸🇻", label: "السلفادور" },
  { iso: "GQ", code: "240", flag: "🇬🇶", label: "غينيا الاستوائية" },
  { iso: "ER", code: "291", flag: "🇪🇷", label: "إريتريا" },
  { iso: "EE", code: "372", flag: "🇪🇪", label: "إستونيا" },
  { iso: "ET", code: "251", flag: "🇪🇹", label: "إثيوبيا" },
  { iso: "FJ", code: "679", flag: "🇫🇯", label: "فيجي" },
  { iso: "FI", code: "358", flag: "🇫🇮", label: "فنلندا" },
  { iso: "FR", code: "33", flag: "🇫🇷", label: "فرنسا" },
  { iso: "GF", code: "594", flag: "🇬🇫", label: "غويانا الفرنسية" },
  { iso: "PF", code: "689", flag: "🇵🇫", label: "بولينيزيا الفرنسية" },
  { iso: "GA", code: "241", flag: "🇬🇦", label: "الغابون" },
  { iso: "GM", code: "220", flag: "🇬🇲", label: "غامبيا" },
  { iso: "GE", code: "995", flag: "🇬🇪", label: "جورجيا" },
  { iso: "DE", code: "49", flag: "🇩🇪", label: "ألمانيا" },
  { iso: "GH", code: "233", flag: "🇬🇭", label: "غانا" },
  { iso: "GR", code: "30", flag: "🇬🇷", label: "اليونان" },
  { iso: "GL", code: "299", flag: "🇬🇱", label: "غرينلاند" },
  { iso: "GD", code: "1", flag: "🇬🇩", label: "غرينادا" },
  { iso: "GP", code: "590", flag: "🇬🇵", label: "غوادلوب" },
  { iso: "GU", code: "1", flag: "🇬🇺", label: "غوام" },
  { iso: "GT", code: "502", flag: "🇬🇹", label: "غواتيمالا" },
  { iso: "GN", code: "224", flag: "🇬🇳", label: "غينيا" },
  { iso: "GW", code: "245", flag: "🇬🇼", label: "غينيا بيساو" },
  { iso: "GY", code: "592", flag: "🇬🇾", label: "غيانا" },
  { iso: "HT", code: "509", flag: "🇭🇹", label: "هايتي" },
  { iso: "HN", code: "504", flag: "🇭🇳", label: "هندوراس" },
  { iso: "HK", code: "852", flag: "🇭🇰", label: "هونغ كونغ" },
  { iso: "HU", code: "36", flag: "🇭🇺", label: "المجر" },
  { iso: "IS", code: "354", flag: "🇮🇸", label: "آيسلندا" },
  { iso: "IN", code: "91", flag: "🇮🇳", label: "الهند" },
  { iso: "ID", code: "62", flag: "🇮🇩", label: "إندونيسيا" },
  { iso: "IR", code: "98", flag: "🇮🇷", label: "إيران" },
  { iso: "IE", code: "353", flag: "🇮🇪", label: "أيرلندا" },
  { iso: "IT", code: "39", flag: "🇮🇹", label: "إيطاليا" },
  { iso: "JM", code: "1", flag: "🇯🇲", label: "جامايكا" },
  { iso: "JP", code: "81", flag: "🇯🇵", label: "اليابان" },
  { iso: "KZ", code: "7", flag: "🇰🇿", label: "كازاخستان" },
  { iso: "KE", code: "254", flag: "🇰🇪", label: "كينيا" },
  { iso: "KI", code: "686", flag: "🇰🇮", label: "كيريباتي" },
  { iso: "KG", code: "996", flag: "🇰🇬", label: "قرغيزستان" },
  { iso: "LA", code: "856", flag: "🇱🇦", label: "لاوس" },
  { iso: "LV", code: "371", flag: "🇱🇻", label: "لاتفيا" },
  { iso: "LS", code: "266", flag: "🇱🇸", label: "ليسوتو" },
  { iso: "LR", code: "231", flag: "🇱🇷", label: "ليبيريا" },
  { iso: "LI", code: "423", flag: "🇱🇮", label: "ليختنشتاين" },
  { iso: "LT", code: "370", flag: "🇱🇹", label: "ليتوانيا" },
  { iso: "LU", code: "352", flag: "🇱🇺", label: "لوكسمبورغ" },
  { iso: "MO", code: "853", flag: "🇲🇴", label: "ماكاو" },
  { iso: "MG", code: "261", flag: "🇲🇬", label: "مدغشقر" },
  { iso: "MW", code: "265", flag: "🇲🇼", label: "مالاوي" },
  { iso: "MY", code: "60", flag: "🇲🇾", label: "ماليزيا" },
  { iso: "MV", code: "960", flag: "🇲🇻", label: "المالديف" },
  { iso: "ML", code: "223", flag: "🇲🇱", label: "مالي" },
  { iso: "MT", code: "356", flag: "🇲🇹", label: "مالطا" },
  { iso: "MQ", code: "596", flag: "🇲🇶", label: "مارتينيك" },
  { iso: "MU", code: "230", flag: "🇲🇺", label: "موريشيوس" },
  { iso: "MX", code: "52", flag: "🇲🇽", label: "المكسيك" },
  { iso: "FM", code: "691", flag: "🇫🇲", label: "ميكرونيزيا" },
  { iso: "MD", code: "373", flag: "🇲🇩", label: "مولدوفا" },
  { iso: "MC", code: "377", flag: "🇲🇨", label: "موناكو" },
  { iso: "MN", code: "976", flag: "🇲🇳", label: "منغوليا" },
  { iso: "ME", code: "382", flag: "🇲🇪", label: "الجبل الأسود" },
  { iso: "MS", code: "1", flag: "🇲🇸", label: "مونتسرات" },
  { iso: "MZ", code: "258", flag: "🇲🇿", label: "موزمبيق" },
  { iso: "MM", code: "95", flag: "🇲🇲", label: "ميانمار" },
  { iso: "NA", code: "264", flag: "🇳🇦", label: "ناميبيا" },
  { iso: "NR", code: "674", flag: "🇳🇷", label: "ناورو" },
  { iso: "NP", code: "977", flag: "🇳🇵", label: "نيبال" },
  { iso: "NL", code: "31", flag: "🇳🇱", label: "هولندا" },
  { iso: "NC", code: "687", flag: "🇳🇨", label: "كاليدونيا الجديدة" },
  { iso: "NZ", code: "64", flag: "🇳🇿", label: "نيوزيلندا" },
  { iso: "NI", code: "505", flag: "🇳🇮", label: "نيكاراغوا" },
  { iso: "NE", code: "227", flag: "🇳🇪", label: "النيجر" },
  { iso: "NG", code: "234", flag: "🇳🇬", label: "نيجيريا" },
  { iso: "KP", code: "850", flag: "🇰🇵", label: "كوريا الشمالية" },
  { iso: "MK", code: "389", flag: "🇲🇰", label: "مقدونيا الشمالية" },
  { iso: "NO", code: "47", flag: "🇳🇴", label: "النرويج" },
  { iso: "PK", code: "92", flag: "🇵🇰", label: "باكستان" },
  { iso: "PW", code: "680", flag: "🇵🇼", label: "بالاو" },
  { iso: "PA", code: "507", flag: "🇵🇦", label: "بنما" },
  { iso: "PG", code: "675", flag: "🇵🇬", label: "بابوا غينيا الجديدة" },
  { iso: "PY", code: "595", flag: "🇵🇾", label: "باراغواي" },
  { iso: "PE", code: "51", flag: "🇵🇪", label: "بيرو" },
  { iso: "PH", code: "63", flag: "🇵🇭", label: "الفلبين" },
  { iso: "PL", code: "48", flag: "🇵🇱", label: "بولندا" },
  { iso: "PT", code: "351", flag: "🇵🇹", label: "البرتغال" },
  { iso: "PR", code: "1", flag: "🇵🇷", label: "بورتوريكو" },
  { iso: "RO", code: "40", flag: "🇷🇴", label: "رومانيا" },
  { iso: "RU", code: "7", flag: "🇷🇺", label: "روسيا" },
  { iso: "RW", code: "250", flag: "🇷🇼", label: "رواندا" },
  { iso: "WS", code: "685", flag: "🇼🇸", label: "ساموا" },
  { iso: "SM", code: "378", flag: "🇸🇲", label: "سان مارينو" },
  { iso: "SN", code: "221", flag: "🇸🇳", label: "السنغال" },
  { iso: "RS", code: "381", flag: "🇷🇸", label: "صربيا" },
  { iso: "SC", code: "248", flag: "🇸🇨", label: "سيشل" },
  { iso: "SL", code: "232", flag: "🇸🇱", label: "سيراليون" },
  { iso: "SG", code: "65", flag: "🇸🇬", label: "سنغافورة" },
  { iso: "SK", code: "421", flag: "🇸🇰", label: "سلوفاكيا" },
  { iso: "SI", code: "386", flag: "🇸🇮", label: "سلوفينيا" },
  { iso: "SB", code: "677", flag: "🇸🇧", label: "جزر سليمان" },
  { iso: "ZA", code: "27", flag: "🇿🇦", label: "جنوب أفريقيا" },
  { iso: "KR", code: "82", flag: "🇰🇷", label: "كوريا الجنوبية" },
  { iso: "SS", code: "211", flag: "🇸🇸", label: "جنوب السودان" },
  { iso: "ES", code: "34", flag: "🇪🇸", label: "إسبانيا" },
  { iso: "LK", code: "94", flag: "🇱🇰", label: "سريلانكا" },
  { iso: "SR", code: "597", flag: "🇸🇷", label: "سورينام" },
  { iso: "SZ", code: "268", flag: "🇸🇿", label: "إسواتيني" },
  { iso: "SE", code: "46", flag: "🇸🇪", label: "السويد" },
  { iso: "CH", code: "41", flag: "🇨🇭", label: "سويسرا" },
  { iso: "TW", code: "886", flag: "🇹🇼", label: "تايوان" },
  { iso: "TJ", code: "992", flag: "🇹🇯", label: "طاجيكستان" },
  { iso: "TZ", code: "255", flag: "🇹🇿", label: "تنزانيا" },
  { iso: "TH", code: "66", flag: "🇹🇭", label: "تايلاند" },
  { iso: "TL", code: "670", flag: "🇹🇱", label: "تيمور الشرقية" },
  { iso: "TG", code: "228", flag: "🇹🇬", label: "توغو" },
  { iso: "TO", code: "676", flag: "🇹🇴", label: "تونغا" },
  { iso: "TT", code: "1", flag: "🇹🇹", label: "ترينيداد وتوباغو" },
  { iso: "TM", code: "993", flag: "🇹🇲", label: "تركمانستان" },
  { iso: "TC", code: "1", flag: "🇹🇨", label: "تركس وكايكوس" },
  { iso: "UG", code: "256", flag: "🇺🇬", label: "أوغندا" },
  { iso: "UA", code: "380", flag: "🇺🇦", label: "أوكرانيا" },
  { iso: "UY", code: "598", flag: "🇺🇾", label: "أوروغواي" },
  { iso: "UZ", code: "998", flag: "🇺🇿", label: "أوزبكستان" },
  { iso: "VU", code: "678", flag: "🇻🇺", label: "فانواتو" },
  { iso: "VA", code: "39", flag: "🇻🇦", label: "الفاتيكان" },
  { iso: "VE", code: "58", flag: "🇻🇪", label: "فنزويلا" },
  { iso: "VN", code: "84", flag: "🇻🇳", label: "فيتنام" },
  { iso: "VI", code: "1", flag: "🇻🇮", label: "جزر العذراء الأمريكية" },
  { iso: "ZM", code: "260", flag: "🇿🇲", label: "زامبيا" },
  { iso: "ZW", code: "263", flag: "🇿🇼", label: "زيمبابوي" },
];

export const KNOWN_PHONE_COUNTRY_CODES = Array.from(
  new Set(PHONE_COUNTRIES.map((country) => country.code))
).sort((a, b) => b.length - a.length);
